version: '3'

services:
  db:
    container_name: quote_editor_db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
  redis:
    container_name: quote_editor_redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  # web:
  #   container_name: quote_editor_web
  #   build: .
  #   # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - '.:/rails'
  #   environment:
  #     - DATABASE_HOST=db
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - db

volumes:
  postgres:
  redis:
